apiVersion: v1
kind: Service
metadata:
  name: wealth-advisory-copilot
  labels:
    app: wealth-advisory-copilot
spec:
  selector:
    app: wealth-advisory-copilot
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP
